language: rust
rust: nightly
sudo: false

cache:
  - cargo

script:
  - rustup target add wasm32-unknown-unknown
  - cargo build --target wasm32-unknown-unknown
  - cargo install wasm-bindgen
  - wasm-bindgen --out-dir www --target web --reference-types --no-typescript --omit-default-module-path target/wasm32-unknown-unknown/debug/wasm_game_of_life.wasm
